<?php

namespace Tasch\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PoemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoemRepository extends EntityRepository
{
}
